//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfb.CandidatePortal.Web.WebApplication.Controls {
    
    
    public partial class CommitteeProfile {
        
        /// <summary>
        /// _errorMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label _errorMessage;
        
        /// <summary>
        /// _committeePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel _committeePanel;
        
        /// <summary>
        /// _committeeSelection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList _committeeSelection;
        
        /// <summary>
        /// _singleCommittee control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label _singleCommittee;
        
        /// <summary>
        /// _committeeDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel _committeeDetails;
        
        /// <summary>
        /// _StreetNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _StreetNumber;
        
        /// <summary>
        /// _StreetName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _StreetName;
        
        /// <summary>
        /// _Apartment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _Apartment;
        
        /// <summary>
        /// _City control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _City;
        
        /// <summary>
        /// _State control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _State;
        
        /// <summary>
        /// _Zip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _Zip;
        
        /// <summary>
        /// _email control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _email;
        
        /// <summary>
        /// _webUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _webUrl;
        
        /// <summary>
        /// _principal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _principal;
        
        /// <summary>
        /// _active control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _active;
        
        /// <summary>
        /// _daytimePhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _daytimePhone;
        
        /// <summary>
        /// _eveningPhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _eveningPhone;
        
        /// <summary>
        /// _fax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _fax;
        
        /// <summary>
        /// _boeDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _boeDate;
        
        /// <summary>
        /// _terminationDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _terminationDate;
        
        /// <summary>
        /// _mailingLine1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _mailingLine1;
        
        /// <summary>
        /// _mailingStreetNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _mailingStreetNumber;
        
        /// <summary>
        /// _mailingStreetName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _mailingStreetName;
        
        /// <summary>
        /// _mailingApartment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _mailingApartment;
        
        /// <summary>
        /// _mailingCity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _mailingCity;
        
        /// <summary>
        /// _mailingState control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _mailingState;
        
        /// <summary>
        /// _mailingZip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _mailingZip;
        
        /// <summary>
        /// _salutation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _salutation;
        
        /// <summary>
        /// _lastName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _lastName;
        
        /// <summary>
        /// _firstName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _firstName;
        
        /// <summary>
        /// _mi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _mi;
        
        /// <summary>
        /// _contactOrder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _contactOrder;
        
        /// <summary>
        /// _treasStreetNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _treasStreetNumber;
        
        /// <summary>
        /// _treasStreetName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _treasStreetName;
        
        /// <summary>
        /// _treasApartment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _treasApartment;
        
        /// <summary>
        /// _treasCity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _treasCity;
        
        /// <summary>
        /// _treasState control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _treasState;
        
        /// <summary>
        /// _treasZip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _treasZip;
        
        /// <summary>
        /// _treasDaytimePhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _treasDaytimePhone;
        
        /// <summary>
        /// _treasEveningPhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _treasEveningPhone;
        
        /// <summary>
        /// _treasFax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _treasFax;
        
        /// <summary>
        /// _treasEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _treasEmail;
        
        /// <summary>
        /// _empName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _empName;
        
        /// <summary>
        /// _empStreetNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _empStreetNumber;
        
        /// <summary>
        /// _empStreetName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _empStreetName;
        
        /// <summary>
        /// _empCity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _empCity;
        
        /// <summary>
        /// _empState control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _empState;
        
        /// <summary>
        /// _empZip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _empZip;
        
        /// <summary>
        /// _empPhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _empPhone;
        
        /// <summary>
        /// _empFax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _empFax;
        
        /// <summary>
        /// _lastDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _lastDate;
        
        /// <summary>
        /// _lastOffice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _lastOffice;
        
        /// <summary>
        /// _lastDistrict control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _lastDistrict;
        
        /// <summary>
        /// _lastParty control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _lastParty;
        
        /// <summary>
        /// _liaisonList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList _liaisonList;
        
        /// <summary>
        /// _liaisonUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel _liaisonUpdatePanel;
        
        /// <summary>
        /// _liaisonError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label _liaisonError;
        
        /// <summary>
        /// _liaisonDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel _liaisonDetails;
        
        /// <summary>
        /// _liaisonSalutation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _liaisonSalutation;
        
        /// <summary>
        /// _liaisonLastName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _liaisonLastName;
        
        /// <summary>
        /// _liaisonFirstName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _liaisonFirstName;
        
        /// <summary>
        /// _liaisonMiddleInitial control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _liaisonMiddleInitial;
        
        /// <summary>
        /// _liaisonOrder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _liaisonOrder;
        
        /// <summary>
        /// _liaisonStreetNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _liaisonStreetNumber;
        
        /// <summary>
        /// _liaisonStreetName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _liaisonStreetName;
        
        /// <summary>
        /// _liaisonApartment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _liaisonApartment;
        
        /// <summary>
        /// _liaisonCity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _liaisonCity;
        
        /// <summary>
        /// _liaisonState control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _liaisonState;
        
        /// <summary>
        /// _liaisonZip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _liaisonZip;
        
        /// <summary>
        /// _liaisonDaytimePhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _liaisonDaytimePhone;
        
        /// <summary>
        /// _liaisonEveningPhone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _liaisonEveningPhone;
        
        /// <summary>
        /// _liaisonFax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _liaisonFax;
        
        /// <summary>
        /// _liaisonEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _liaisonEmail;
        
        /// <summary>
        /// _liaisonType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _liaisonType;
        
        /// <summary>
        /// _liaisonManagerial control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _liaisonManagerial;
        
        /// <summary>
        /// _liaisonVG control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _liaisonVG;
        
        /// <summary>
        /// _entityName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _entityName;
        
        /// <summary>
        /// _bankAccountsList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList _bankAccountsList;
        
        /// <summary>
        /// _bankAccountsUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel _bankAccountsUpdatePanel;
        
        /// <summary>
        /// _bankError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label _bankError;
        
        /// <summary>
        /// _bankAccountDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel _bankAccountDetails;
        
        /// <summary>
        /// _bankName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _bankName;
        
        /// <summary>
        /// _bankCity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _bankCity;
        
        /// <summary>
        /// _bankState control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _bankState;
        
        /// <summary>
        /// _bankZip control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _bankZip;
        
        /// <summary>
        /// _accountNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _accountNumber;
        
        /// <summary>
        /// _accountName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _accountName;
        
        /// <summary>
        /// _accountType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _accountType;
        
        /// <summary>
        /// _accountPurpose control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _accountPurpose;
        
        /// <summary>
        /// _dateOpened control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _dateOpened;
        
        /// <summary>
        /// _dateClosed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _dateClosed;
        
        /// <summary>
        /// _balance control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _balance;
        
        /// <summary>
        /// _balanceDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _balanceDate;
        
        /// <summary>
        /// _directDeposit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.FormField _directDeposit;
    }
}
