//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Cfb.CandidatePortal.Data.SecurityModel", "FK_SecurityGroupMembership_SecurityGroups", "SecurityGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cfb.CandidatePortal.Data.SecurityGroup), "SecurityGroupMembership", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cfb.CandidatePortal.Data.SecurityGroupMembership), true)]
[assembly: EdmRelationshipAttribute("Cfb.CandidatePortal.Data.SecurityModel", "FK_SecuritySsoTokens_SecuritySsoApplications", "SecuritySsoApplication", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cfb.CandidatePortal.Data.SecuritySsoApplication), "SecuritySsoToken", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cfb.CandidatePortal.Data.SecuritySsoToken))]

#endregion

namespace Cfb.CandidatePortal.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CPSecurityEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CPSecurityEntities object using the connection string found in the 'CPSecurityEntities' section of the application configuration file.
        /// </summary>
        public CPSecurityEntities() : base("name=CPSecurityEntities", "CPSecurityEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CPSecurityEntities object.
        /// </summary>
        public CPSecurityEntities(string connectionString) : base(connectionString, "CPSecurityEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CPSecurityEntities object.
        /// </summary>
        public CPSecurityEntities(EntityConnection connection) : base(connection, "CPSecurityEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SecurityUserElectionCycle> SecurityUserElectionCycles
        {
            get
            {
                if ((_SecurityUserElectionCycles == null))
                {
                    _SecurityUserElectionCycles = base.CreateObjectSet<SecurityUserElectionCycle>("SecurityUserElectionCycles");
                }
                return _SecurityUserElectionCycles;
            }
        }
        private ObjectSet<SecurityUserElectionCycle> _SecurityUserElectionCycles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SecurityGroupMembership> SecurityGroupMemberships
        {
            get
            {
                if ((_SecurityGroupMemberships == null))
                {
                    _SecurityGroupMemberships = base.CreateObjectSet<SecurityGroupMembership>("SecurityGroupMemberships");
                }
                return _SecurityGroupMemberships;
            }
        }
        private ObjectSet<SecurityGroupMembership> _SecurityGroupMemberships;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SecurityGroup> SecurityGroups
        {
            get
            {
                if ((_SecurityGroups == null))
                {
                    _SecurityGroups = base.CreateObjectSet<SecurityGroup>("SecurityGroups");
                }
                return _SecurityGroups;
            }
        }
        private ObjectSet<SecurityGroup> _SecurityGroups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SecuritySsoToken> SecuritySsoTokens
        {
            get
            {
                if ((_SecuritySsoTokens == null))
                {
                    _SecuritySsoTokens = base.CreateObjectSet<SecuritySsoToken>("SecuritySsoTokens");
                }
                return _SecuritySsoTokens;
            }
        }
        private ObjectSet<SecuritySsoToken> _SecuritySsoTokens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SecuritySsoApplication> SecuritySsoApplications
        {
            get
            {
                if ((_SecuritySsoApplications == null))
                {
                    _SecuritySsoApplications = base.CreateObjectSet<SecuritySsoApplication>("SecuritySsoApplications");
                }
                return _SecuritySsoApplications;
            }
        }
        private ObjectSet<SecuritySsoApplication> _SecuritySsoApplications;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SecurityUserProfile> SecurityUserProfiles
        {
            get
            {
                if ((_SecurityUserProfiles == null))
                {
                    _SecurityUserProfiles = base.CreateObjectSet<SecurityUserProfile>("SecurityUserProfiles");
                }
                return _SecurityUserProfiles;
            }
        }
        private ObjectSet<SecurityUserProfile> _SecurityUserProfiles;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SecurityUserElectionCycles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSecurityUserElectionCycles(SecurityUserElectionCycle securityUserElectionCycle)
        {
            base.AddObject("SecurityUserElectionCycles", securityUserElectionCycle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SecurityGroupMemberships EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSecurityGroupMemberships(SecurityGroupMembership securityGroupMembership)
        {
            base.AddObject("SecurityGroupMemberships", securityGroupMembership);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SecurityGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSecurityGroups(SecurityGroup securityGroup)
        {
            base.AddObject("SecurityGroups", securityGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SecuritySsoTokens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSecuritySsoTokens(SecuritySsoToken securitySsoToken)
        {
            base.AddObject("SecuritySsoTokens", securitySsoToken);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SecuritySsoApplications EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSecuritySsoApplications(SecuritySsoApplication securitySsoApplication)
        {
            base.AddObject("SecuritySsoApplications", securitySsoApplication);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SecurityUserProfiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSecurityUserProfiles(SecurityUserProfile securityUserProfile)
        {
            base.AddObject("SecurityUserProfiles", securityUserProfile);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Cfb.CandidatePortal.Data.SecurityModel", Name="SecurityGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SecurityGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SecurityGroup object.
        /// </summary>
        /// <param name="groupId">Initial value of the GroupId property.</param>
        /// <param name="groupName">Initial value of the GroupName property.</param>
        /// <param name="userRights">Initial value of the UserRights property.</param>
        public static SecurityGroup CreateSecurityGroup(global::System.Byte groupId, global::System.String groupName, global::System.Int32 userRights)
        {
            SecurityGroup securityGroup = new SecurityGroup();
            securityGroup.GroupId = groupId;
            securityGroup.GroupName = groupName;
            securityGroup.UserRights = userRights;
            return securityGroup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte GroupId
        {
            get
            {
                return _GroupId;
            }
            set
            {
                if (_GroupId != value)
                {
                    OnGroupIdChanging(value);
                    ReportPropertyChanging("GroupId");
                    _GroupId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GroupId");
                    OnGroupIdChanged();
                }
            }
        }
        private global::System.Byte _GroupId;
        partial void OnGroupIdChanging(global::System.Byte value);
        partial void OnGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GroupName
        {
            get
            {
                return _GroupName;
            }
            set
            {
                OnGroupNameChanging(value);
                ReportPropertyChanging("GroupName");
                _GroupName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GroupName");
                OnGroupNameChanged();
            }
        }
        private global::System.String _GroupName;
        partial void OnGroupNameChanging(global::System.String value);
        partial void OnGroupNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserRights
        {
            get
            {
                return _UserRights;
            }
            set
            {
                OnUserRightsChanging(value);
                ReportPropertyChanging("UserRights");
                _UserRights = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserRights");
                OnUserRightsChanged();
            }
        }
        private global::System.Int32 _UserRights;
        partial void OnUserRightsChanging(global::System.Int32 value);
        partial void OnUserRightsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Cfb.CandidatePortal.Data.SecurityModel", "FK_SecurityGroupMembership_SecurityGroups", "SecurityGroupMembership")]
        public EntityCollection<SecurityGroupMembership> SecurityGroupMemberships
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SecurityGroupMembership>("Cfb.CandidatePortal.Data.SecurityModel.FK_SecurityGroupMembership_SecurityGroups", "SecurityGroupMembership");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SecurityGroupMembership>("Cfb.CandidatePortal.Data.SecurityModel.FK_SecurityGroupMembership_SecurityGroups", "SecurityGroupMembership", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Cfb.CandidatePortal.Data.SecurityModel", Name="SecurityGroupMembership")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SecurityGroupMembership : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SecurityGroupMembership object.
        /// </summary>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="groupId">Initial value of the GroupId property.</param>
        public static SecurityGroupMembership CreateSecurityGroupMembership(global::System.String userName, global::System.Byte groupId)
        {
            SecurityGroupMembership securityGroupMembership = new SecurityGroupMembership();
            securityGroupMembership.UserName = userName;
            securityGroupMembership.GroupId = groupId;
            return securityGroupMembership;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                if (_UserName != value)
                {
                    OnUserNameChanging(value);
                    ReportPropertyChanging("UserName");
                    _UserName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserName");
                    OnUserNameChanged();
                }
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte GroupId
        {
            get
            {
                return _GroupId;
            }
            set
            {
                if (_GroupId != value)
                {
                    OnGroupIdChanging(value);
                    ReportPropertyChanging("GroupId");
                    _GroupId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GroupId");
                    OnGroupIdChanged();
                }
            }
        }
        private global::System.Byte _GroupId;
        partial void OnGroupIdChanging(global::System.Byte value);
        partial void OnGroupIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Cfb.CandidatePortal.Data.SecurityModel", "FK_SecurityGroupMembership_SecurityGroups", "SecurityGroup")]
        public SecurityGroup SecurityGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SecurityGroup>("Cfb.CandidatePortal.Data.SecurityModel.FK_SecurityGroupMembership_SecurityGroups", "SecurityGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SecurityGroup>("Cfb.CandidatePortal.Data.SecurityModel.FK_SecurityGroupMembership_SecurityGroups", "SecurityGroup").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SecurityGroup> SecurityGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SecurityGroup>("Cfb.CandidatePortal.Data.SecurityModel.FK_SecurityGroupMembership_SecurityGroups", "SecurityGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SecurityGroup>("Cfb.CandidatePortal.Data.SecurityModel.FK_SecurityGroupMembership_SecurityGroups", "SecurityGroup", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Cfb.CandidatePortal.Data.SecurityModel", Name="SecuritySsoApplication")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SecuritySsoApplication : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SecuritySsoApplication object.
        /// </summary>
        /// <param name="applicationId">Initial value of the ApplicationId property.</param>
        /// <param name="applicationName">Initial value of the ApplicationName property.</param>
        /// <param name="userRights">Initial value of the UserRights property.</param>
        public static SecuritySsoApplication CreateSecuritySsoApplication(global::System.Byte applicationId, global::System.String applicationName, global::System.Int32 userRights)
        {
            SecuritySsoApplication securitySsoApplication = new SecuritySsoApplication();
            securitySsoApplication.ApplicationId = applicationId;
            securitySsoApplication.ApplicationName = applicationName;
            securitySsoApplication.UserRights = userRights;
            return securitySsoApplication;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte ApplicationId
        {
            get
            {
                return _ApplicationId;
            }
            set
            {
                if (_ApplicationId != value)
                {
                    OnApplicationIdChanging(value);
                    ReportPropertyChanging("ApplicationId");
                    _ApplicationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ApplicationId");
                    OnApplicationIdChanged();
                }
            }
        }
        private global::System.Byte _ApplicationId;
        partial void OnApplicationIdChanging(global::System.Byte value);
        partial void OnApplicationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ApplicationName
        {
            get
            {
                return _ApplicationName;
            }
            set
            {
                OnApplicationNameChanging(value);
                ReportPropertyChanging("ApplicationName");
                _ApplicationName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ApplicationName");
                OnApplicationNameChanged();
            }
        }
        private global::System.String _ApplicationName;
        partial void OnApplicationNameChanging(global::System.String value);
        partial void OnApplicationNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserRights
        {
            get
            {
                return _UserRights;
            }
            set
            {
                OnUserRightsChanging(value);
                ReportPropertyChanging("UserRights");
                _UserRights = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserRights");
                OnUserRightsChanged();
            }
        }
        private global::System.Int32 _UserRights;
        partial void OnUserRightsChanging(global::System.Int32 value);
        partial void OnUserRightsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RedirectUrl
        {
            get
            {
                return _RedirectUrl;
            }
            set
            {
                OnRedirectUrlChanging(value);
                ReportPropertyChanging("RedirectUrl");
                _RedirectUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RedirectUrl");
                OnRedirectUrlChanged();
            }
        }
        private global::System.String _RedirectUrl;
        partial void OnRedirectUrlChanging(global::System.String value);
        partial void OnRedirectUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TokenParameter
        {
            get
            {
                return _TokenParameter;
            }
            set
            {
                OnTokenParameterChanging(value);
                ReportPropertyChanging("TokenParameter");
                _TokenParameter = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TokenParameter");
                OnTokenParameterChanged();
            }
        }
        private global::System.String _TokenParameter;
        partial void OnTokenParameterChanging(global::System.String value);
        partial void OnTokenParameterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LoginPagePath
        {
            get
            {
                return _LoginPagePath;
            }
            set
            {
                OnLoginPagePathChanging(value);
                ReportPropertyChanging("LoginPagePath");
                _LoginPagePath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LoginPagePath");
                OnLoginPagePathChanged();
            }
        }
        private global::System.String _LoginPagePath;
        partial void OnLoginPagePathChanging(global::System.String value);
        partial void OnLoginPagePathChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Cfb.CandidatePortal.Data.SecurityModel", "FK_SecuritySsoTokens_SecuritySsoApplications", "SecuritySsoToken")]
        public EntityCollection<SecuritySsoToken> SecuritySsoTokens
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SecuritySsoToken>("Cfb.CandidatePortal.Data.SecurityModel.FK_SecuritySsoTokens_SecuritySsoApplications", "SecuritySsoToken");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SecuritySsoToken>("Cfb.CandidatePortal.Data.SecurityModel.FK_SecuritySsoTokens_SecuritySsoApplications", "SecuritySsoToken", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Cfb.CandidatePortal.Data.SecurityModel", Name="SecuritySsoToken")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SecuritySsoToken : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SecuritySsoToken object.
        /// </summary>
        /// <param name="tokenId">Initial value of the TokenId property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        public static SecuritySsoToken CreateSecuritySsoToken(global::System.Guid tokenId, global::System.String userName, global::System.DateTime created)
        {
            SecuritySsoToken securitySsoToken = new SecuritySsoToken();
            securitySsoToken.TokenId = tokenId;
            securitySsoToken.UserName = userName;
            securitySsoToken.Created = created;
            return securitySsoToken;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TokenId
        {
            get
            {
                return _TokenId;
            }
            set
            {
                if (_TokenId != value)
                {
                    OnTokenIdChanging(value);
                    ReportPropertyChanging("TokenId");
                    _TokenId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TokenId");
                    OnTokenIdChanged();
                }
            }
        }
        private global::System.Guid _TokenId;
        partial void OnTokenIdChanging(global::System.Guid value);
        partial void OnTokenIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Cfb.CandidatePortal.Data.SecurityModel", "FK_SecuritySsoTokens_SecuritySsoApplications", "SecuritySsoApplication")]
        public SecuritySsoApplication SecuritySsoApplication
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SecuritySsoApplication>("Cfb.CandidatePortal.Data.SecurityModel.FK_SecuritySsoTokens_SecuritySsoApplications", "SecuritySsoApplication").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SecuritySsoApplication>("Cfb.CandidatePortal.Data.SecurityModel.FK_SecuritySsoTokens_SecuritySsoApplications", "SecuritySsoApplication").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SecuritySsoApplication> SecuritySsoApplicationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SecuritySsoApplication>("Cfb.CandidatePortal.Data.SecurityModel.FK_SecuritySsoTokens_SecuritySsoApplications", "SecuritySsoApplication");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SecuritySsoApplication>("Cfb.CandidatePortal.Data.SecurityModel.FK_SecuritySsoTokens_SecuritySsoApplications", "SecuritySsoApplication", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Cfb.CandidatePortal.Data.SecurityModel", Name="SecurityUserElectionCycle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SecurityUserElectionCycle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SecurityUserElectionCycle object.
        /// </summary>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="electionCycle">Initial value of the ElectionCycle property.</param>
        public static SecurityUserElectionCycle CreateSecurityUserElectionCycle(global::System.String userName, global::System.String electionCycle)
        {
            SecurityUserElectionCycle securityUserElectionCycle = new SecurityUserElectionCycle();
            securityUserElectionCycle.UserName = userName;
            securityUserElectionCycle.ElectionCycle = electionCycle;
            return securityUserElectionCycle;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                if (_UserName != value)
                {
                    OnUserNameChanging(value);
                    ReportPropertyChanging("UserName");
                    _UserName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserName");
                    OnUserNameChanged();
                }
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ElectionCycle
        {
            get
            {
                return _ElectionCycle;
            }
            set
            {
                if (_ElectionCycle != value)
                {
                    OnElectionCycleChanging(value);
                    ReportPropertyChanging("ElectionCycle");
                    _ElectionCycle = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ElectionCycle");
                    OnElectionCycleChanged();
                }
            }
        }
        private global::System.String _ElectionCycle;
        partial void OnElectionCycleChanging(global::System.String value);
        partial void OnElectionCycleChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Cfb.CandidatePortal.Data.SecurityModel", Name="SecurityUserProfile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SecurityUserProfile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SecurityUserProfile object.
        /// </summary>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="candidateId">Initial value of the CandidateId property.</param>
        /// <param name="passwordExpired">Initial value of the PasswordExpired property.</param>
        /// <param name="cfisType">Initial value of the CfisType property.</param>
        public static SecurityUserProfile CreateSecurityUserProfile(global::System.String userName, global::System.String candidateId, global::System.Boolean passwordExpired, global::System.Byte cfisType)
        {
            SecurityUserProfile securityUserProfile = new SecurityUserProfile();
            securityUserProfile.UserName = userName;
            securityUserProfile.CandidateId = candidateId;
            securityUserProfile.PasswordExpired = passwordExpired;
            securityUserProfile.CfisType = cfisType;
            return securityUserProfile;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                if (_UserName != value)
                {
                    OnUserNameChanging(value);
                    ReportPropertyChanging("UserName");
                    _UserName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserName");
                    OnUserNameChanged();
                }
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DisplayName
        {
            get
            {
                return _DisplayName;
            }
            set
            {
                OnDisplayNameChanging(value);
                ReportPropertyChanging("DisplayName");
                _DisplayName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DisplayName");
                OnDisplayNameChanged();
            }
        }
        private global::System.String _DisplayName;
        partial void OnDisplayNameChanging(global::System.String value);
        partial void OnDisplayNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CandidateId
        {
            get
            {
                return _CandidateId;
            }
            set
            {
                OnCandidateIdChanging(value);
                ReportPropertyChanging("CandidateId");
                _CandidateId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CandidateId");
                OnCandidateIdChanged();
            }
        }
        private global::System.String _CandidateId;
        partial void OnCandidateIdChanging(global::System.String value);
        partial void OnCandidateIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PasswordExpired
        {
            get
            {
                return _PasswordExpired;
            }
            set
            {
                OnPasswordExpiredChanging(value);
                ReportPropertyChanging("PasswordExpired");
                _PasswordExpired = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PasswordExpired");
                OnPasswordExpiredChanged();
            }
        }
        private global::System.Boolean _PasswordExpired;
        partial void OnPasswordExpiredChanging(global::System.Boolean value);
        partial void OnPasswordExpiredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte CfisType
        {
            get
            {
                return _CfisType;
            }
            set
            {
                OnCfisTypeChanging(value);
                ReportPropertyChanging("CfisType");
                _CfisType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CfisType");
                OnCfisTypeChanged();
            }
        }
        private global::System.Byte _CfisType;
        partial void OnCfisTypeChanging(global::System.Byte value);
        partial void OnCfisTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CfisCommitteeID
        {
            get
            {
                return _CfisCommitteeID;
            }
            set
            {
                OnCfisCommitteeIDChanging(value);
                ReportPropertyChanging("CfisCommitteeID");
                _CfisCommitteeID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CfisCommitteeID");
                OnCfisCommitteeIDChanged();
            }
        }
        private global::System.String _CfisCommitteeID;
        partial void OnCfisCommitteeIDChanging(global::System.String value);
        partial void OnCfisCommitteeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CfisCommitteeContactID
        {
            get
            {
                return _CfisCommitteeContactID;
            }
            set
            {
                OnCfisCommitteeContactIDChanging(value);
                ReportPropertyChanging("CfisCommitteeContactID");
                _CfisCommitteeContactID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CfisCommitteeContactID");
                OnCfisCommitteeContactIDChanged();
            }
        }
        private global::System.String _CfisCommitteeContactID;
        partial void OnCfisCommitteeContactIDChanging(global::System.String value);
        partial void OnCfisCommitteeContactIDChanged();

        #endregion
    
    }

    #endregion
    
}
