//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfb.CandidatePortal.Net.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<p>The NYC Campaign Finance Board has sent the <strong>{0} {1}</strong> (ID: {2})" +
            " campaign a new {3} message. <strong>This message requires your attention.</stro" +
            "ng></p>")]
        public string CmoMessageTemplate {
            get {
                return ((string)(this["CmoMessageTemplate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<p>The NYC Campaign Finance Board has issued a response to the extension requeste" +
            "d by the <strong>{0} {1}</strong> (ID: {2}) campaign. Please check your C-Access" +
            " account to obtain the details and any modifications to the due date.</p>")]
        public string CmoMessageExtensionTemplate {
            get {
                return ((string)(this["CmoMessageExtensionTemplate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<html>
<body>
<h1><img src=""{2}/images/caccess-logo.png"" width=""113"" height=""29"" alt=""C-Access""/></h1>
<p>Dear {0},</p>
{1}
<p>If you have not yet received or do not know your C-Access username/password, please contact the Candidate Services Unit at (212) 409-1800.</p>
<p><em>NOTE: Please do not reply to this automated message, as e-mail sent to this address will not be answered.</em></p>
</body>
</html>")]
        public string MessageBodyTemplate {
            get {
                return ((string)(this["MessageBodyTemplate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<p>View this message in your C-Access Message Center by clicking the URL below or copying and pasting it in a new browser window:<br/>
<a href=""{0}/Messages/View.aspx?id={1}"" target=""_blank"" title=""View New CFBMessage"">{0}/Messages/View.aspx?id={1}</a></p>")]
        public string CmoMessageViewLinkTemplate {
            get {
                return ((string)(this["CmoMessageViewLinkTemplate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("caccess-messages@nyccfb.info")]
        public string CmoMessageCCEmailAddress {
            get {
                return ((string)(this["CmoMessageCCEmailAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<p>The NYC Campaign Finance Board has sent the <strong>{0} {1}</strong> (ID: {2})" +
            " campaign a new {3} letter. <strong>This letter requires your attention.</strong" +
            "></p>")]
        public string CmoMessageTollingTemplate {
            get {
                return ((string)(this["CmoMessageTollingTemplate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<p>The NYC Campaign Finance Board has sent the <strong>{0} {1}</strong> (ID: {2})" +
            " campaign a new {3}. <strong>This letter requires your attention.</strong></p>")]
        public string CmoMessageInadequateTemplate {
            get {
                return ((string)(this["CmoMessageInadequateTemplate"]));
            }
        }
    }
}
