document.createElement('header');
document.createElement('nav');
document.createElement('section');
document.createElement('details');
document.createElement('summary');
document.createElement('article');
document.createElement('aside');
document.createElement('footer');
document.createElement('hgroup');
