//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfb.CandidatePortal.Web.WebApplication.Audit {
    
    
    public partial class Default {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Cfb.CandidatePortal.Web.WebApplication.Audit.Audit Master {
            get {
                return ((Cfb.CandidatePortal.Web.WebApplication.Audit.Audit)(base.Master));
            }
        }
    }
}
