//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfb.CandidatePortal.Web.WebApplication.Audit {
    
    
    public partial class PostElection {
        
        /// <summary>
        /// _postElectionAuditNavigation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.PostElectionAuditNavigation _postElectionAuditNavigation;
        
        /// <summary>
        /// _reportSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.PostElectionAuditSummary _reportSummary;
        
        /// <summary>
        /// _inadequateSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.PostElectionAuditSummary _inadequateSummary;
        
        /// <summary>
        /// _currentStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label _currentStatus;
        
        /// <summary>
        /// _darOriginalIssueDateLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label _darOriginalIssueDateLabel;
        
        /// <summary>
        /// _darTollingDaysLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label _darTollingDaysLabel;
        
        /// <summary>
        /// _darCurrentIssueDateLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label _darCurrentIssueDateLabel;
        
        /// <summary>
        /// _farOriginalIssueDateLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label _farOriginalIssueDateLabel;
        
        /// <summary>
        /// _farTollingDaysLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label _farTollingDaysLabel;
        
        /// <summary>
        /// _totalTollingDaysLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label _totalTollingDaysLabel;
        
        /// <summary>
        /// TrainingComplianceReference control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl TrainingComplianceReference;
        
        /// <summary>
        /// _farCurrentIssueDateLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label _farCurrentIssueDateLabel;
        
        /// <summary>
        /// TrainingCompliance control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl TrainingCompliance;
        
        /// <summary>
        /// _tollingEventsList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cfb.CandidatePortal.Web.Controls.TollingEventsList _tollingEventsList;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Cfb.CandidatePortal.Web.WebApplication.Audit.Audit Master {
            get {
                return ((Cfb.CandidatePortal.Web.WebApplication.Audit.Audit)(base.Master));
            }
        }
    }
}
