//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cfb.CandidatePortal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CPCalendarItemResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CPCalendarItemResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cfb.CandidatePortal.Properties.CPCalendarItemResources", typeof(CPCalendarItemResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled CFB Compliance Visit.
        /// </summary>
        internal static string CVDescription {
            get {
                return ResourceManager.GetString("CVDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Due for {0} Compliance Visit.
        /// </summary>
        internal static string CVRDDescription {
            get {
                return ResourceManager.GetString("CVRDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comp Visit Resp Due.
        /// </summary>
        internal static string CVRDTitle {
            get {
                return ResourceManager.GetString("CVRDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comp Visit.
        /// </summary>
        internal static string CVTitle {
            get {
                return ResourceManager.GetString("CVTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Election Draft Audit Report.
        /// </summary>
        internal static string DarDescription {
            get {
                return ResourceManager.GetString("DarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Election Draft Audit Report Inadequate Response.
        /// </summary>
        internal static string DarIRDescription {
            get {
                return ResourceManager.GetString("DarIRDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Due for Post Election Draft Audit Report Inadequate Response.
        /// </summary>
        internal static string DarIRRDDescription {
            get {
                return ResourceManager.GetString("DarIRRDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inad DAR Resp Due.
        /// </summary>
        internal static string DarIRRDTitle {
            get {
                return ResourceManager.GetString("DarIRRDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inad DAR Resp.
        /// </summary>
        internal static string DarIRTitle {
            get {
                return ResourceManager.GetString("DarIRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Due for Post Election Draft Audit Report.
        /// </summary>
        internal static string DarRDDescription {
            get {
                return ResourceManager.GetString("DarRDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAR Resp Due.
        /// </summary>
        internal static string DarRDTitle {
            get {
                return ResourceManager.GetString("DarRDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft Audit Report.
        /// </summary>
        internal static string DarTitle {
            get {
                return ResourceManager.GetString("DarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement {0} Doing Business Review.
        /// </summary>
        internal static string DbrDescription {
            get {
                return ResourceManager.GetString("DbrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Due for Statement {0} Doing Business Review.
        /// </summary>
        internal static string DbrRDDescription {
            get {
                return ResourceManager.GetString("DbrRDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stmt {0} DB Resp Due.
        /// </summary>
        internal static string DbrRDTitle {
            get {
                return ResourceManager.GetString("DbrRDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stmt {0} DB Review.
        /// </summary>
        internal static string DbrTitle {
            get {
                return ResourceManager.GetString("DbrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Disclosure Statement {0} Due.
        /// </summary>
        internal static string FilingDateDescription {
            get {
                return ResourceManager.GetString("FilingDateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stmt {0} Filing Day.
        /// </summary>
        internal static string FilingDateTitle {
            get {
                return ResourceManager.GetString("FilingDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Election Documentation Request.
        /// </summary>
        internal static string IdrDescription {
            get {
                return ResourceManager.GetString("IdrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Election Documentation Request Inadequate Response.
        /// </summary>
        internal static string IdrIRDescription {
            get {
                return ResourceManager.GetString("IdrIRDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Due for Post Election Inadequate Documentation Response.
        /// </summary>
        internal static string IdrIRRDDescription {
            get {
                return ResourceManager.GetString("IdrIRRDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inad Doc Resp Due.
        /// </summary>
        internal static string IdrIRRDTitle {
            get {
                return ResourceManager.GetString("IdrIRRDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inad Doc Req Resp.
        /// </summary>
        internal static string IdrIRTitle {
            get {
                return ResourceManager.GetString("IdrIRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Due for Post Election Documentation Request.
        /// </summary>
        internal static string IdrRDDescription {
            get {
                return ResourceManager.GetString("IdrRDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc Req Resp Due.
        /// </summary>
        internal static string IdrRDTitle {
            get {
                return ResourceManager.GetString("IdrRDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc Request.
        /// </summary>
        internal static string IdrTitle {
            get {
                return ResourceManager.GetString("IdrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement {0} Audit Review.
        /// </summary>
        internal static string SRDescription {
            get {
                return ResourceManager.GetString("SRDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Due for Statement {0} Audit Review.
        /// </summary>
        internal static string SRRDDescription {
            get {
                return ResourceManager.GetString("SRRDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stmt {0} Resp Due.
        /// </summary>
        internal static string SRRDTitle {
            get {
                return ResourceManager.GetString("SRRDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stmt {0} Review.
        /// </summary>
        internal static string SRTitle {
            get {
                return ResourceManager.GetString("SRTitle", resourceCulture);
            }
        }
    }
}
